from app import create_app, db
from app.models import Employee

app = create_app()
with app.app_context():
    employees = [
        Employee(name="Иванов Иван", position="Инженер", department="Отдел 1", rating=85, tasks=10, speed=5, correctness=98, score=92),
        Employee(name="Петров Петр", position="Аналитик", department="Отдел 2", rating=90, tasks=12, speed=6, correctness=95, score=93),
        Employee(name="Сидорова Анна", position="Менеджер", department="Отдел 3", rating=88, tasks=8, speed=4, correctness=99, score=90),
        Employee(name="Кузнецова Елена", position="HR", department="Кадры", rating=82, tasks=5, speed=4, correctness=96, score=87),
        Employee(name="Смирнов Алексей", position="DevOps", department="ИТ", rating=93, tasks=14, speed=7, correctness=94, score=95),
        Employee(name="Волкова Мария", position="Бухгалтер", department="Финансы", rating=80, tasks=6, speed=3, correctness=99, score=89),
        Employee(name="Сорокин Денис", position="Тестировщик", department="QA", rating=85, tasks=11, speed=5, correctness=97, score=91),
        Employee(name="Андреев Юрий", position="Дизайнер", department="Маркетинг", rating=77, tasks=7, speed=4, correctness=92, score=84),
        Employee(name="Григорьева Ольга", position="Рекрутер", department="Кадры", rating=79, tasks=6, speed=4, correctness=90, score=83),
        Employee(name="Тихонов Максим", position="Team Lead", department="Разработка", rating=95, tasks=15, speed=8, correctness=96, score=96),
        Employee(name="Зайцева Наталья", position="Контент-менеджер", department="PR", rating=81, tasks=9, speed=5, correctness=94, score=88),
        Employee(name="Морозов Артем", position="Инженер", department="Отдел 1", rating=86, tasks=10, speed=6, correctness=97, score=90),
        Employee(name="Крылова Ирина", position="Аналитик", department="Отдел 2", rating=88, tasks=12, speed=5, correctness=95, score=92),
        Employee(name="Белов Сергей", position="Менеджер", department="Отдел 3", rating=83, tasks=8, speed=4, correctness=93, score=87),
        Employee(name="Ефимова Дарья", position="HR", department="Кадры", rating=80, tasks=5, speed=3, correctness=96, score=85),
        Employee(name="Мельников Никита", position="DevOps", department="ИТ", rating=89, tasks=13, speed=6, correctness=91, score=89),
        Employee(name="Николаева Татьяна", position="Бухгалтер", department="Финансы", rating=82, tasks=6, speed=3, correctness=98, score=88),
        Employee(name="Семенов Владислав", position="Тестировщик", department="QA", rating=84, tasks=10, speed=5, correctness=93, score=86),
        Employee(name="Шестакова Вера", position="Дизайнер", department="Маркетинг", rating=79, tasks=7, speed=4, correctness=95, score=85),
        Employee(name="Федоров Роман", position="Рекрутер", department="Кадры", rating=75, tasks=5, speed=3, correctness=92, score=80),
        Employee(name="Яковлева Ксения", position="Team Lead", department="Разработка", rating=92, tasks=14, speed=7, correctness=97, score=94),
        Employee(name="Панин Дмитрий", position="Контент-менеджер", department="PR", rating=83, tasks=9, speed=5, correctness=90, score=86),
        Employee(name="Капустин Артемий", position="Инженер", department="Отдел 1", rating=87, tasks=11, speed=6, correctness=96, score=90),
        Employee(name="Калинина Ирина", position="Аналитик", department="Отдел 2", rating=89, tasks=13, speed=6, correctness=94, score=91),
        Employee(name="Киселев Виктор", position="Менеджер", department="Отдел 3", rating=84, tasks=9, speed=4, correctness=92, score=87),
        Employee(name="Орлова Надежда", position="HR", department="Кадры", rating=78, tasks=6, speed=3, correctness=94, score=83),
        Employee(name="Гаврилов Егор", position="DevOps", department="ИТ", rating=90, tasks=14, speed=7, correctness=95, score=92),
        Employee(name="Плотникова Анна", position="Бухгалтер", department="Финансы", rating=81, tasks=5, speed=3, correctness=98, score=87),
        Employee(name="Кочетков Иван", position="Тестировщик", department="QA", rating=83, tasks=10, speed=5, correctness=96, score=88),
        Employee(name="Шарова Оксана", position="Дизайнер", department="Маркетинг", rating=80, tasks=8, speed=4, correctness=93, score=85),
        Employee(name="Мещеряков Павел", position="Рекрутер", department="Кадры", rating=76, tasks=6, speed=3, correctness=91, score=82),
        Employee(name="Савельева Лидия", position="Team Lead", department="Разработка", rating=93, tasks=16, speed=8, correctness=97, score=95),
        Employee(name="Назаров Алексей", position="Контент-менеджер", department="PR", rating=84, tasks=9, speed=5, correctness=94, score=89),
        Employee(name="Куликова Яна", position="Инженер", department="Отдел 1", rating=88, tasks=12, speed=6, correctness=95, score=90),
        Employee(name="Жуков Артем", position="Аналитик", department="Отдел 2", rating=91, tasks=14, speed=7, correctness=94, score=93),
        Employee(name="Кондратьева Ирина", position="Менеджер", department="Отдел 3", rating=85, tasks=10, speed=4, correctness=93, score=88),
        Employee(name="Макаров Олег", position="DevOps", department="ИТ", rating=90, tasks=13, speed=7, correctness=96, score=93),
        Employee(name="Громова Ирина", position="HR", department="Кадры", rating=79, tasks=5, speed=3, correctness=95, score=84),
        Employee(name="Гурьев Максим", position="Тестировщик", department="QA", rating=87, tasks=11, speed=6, correctness=92, score=89),
        Employee(name="Захарова Алла", position="Дизайнер", department="Маркетинг", rating=81, tasks=8, speed=4, correctness=94, score=86),
        Employee(name="Романов Валерий", position="Рекрутер", department="Кадры", rating=78, tasks=6, speed=3, correctness=91, score=83),
        Employee(name="Егорова Вера", position="Team Lead", department="Разработка", rating=91, tasks=15, speed=7, correctness=97, score=94),
        Employee(name="Игнатьев Денис", position="Контент-менеджер", department="PR", rating=83, tasks=9, speed=5, correctness=92, score=87),
        Employee(name="Селезнева Анастасия", position="Инженер", department="Отдел 1", rating=86, tasks=11, speed=6, correctness=93, score=89),
        Employee(name="Минаев Андрей", position="Аналитик", department="Отдел 2", rating=89, tasks=13, speed=7, correctness=94, score=92),
        Employee(name="Чернова Лилия", position="Менеджер", department="Отдел 3", rating=84, tasks=9, speed=4, correctness=95, score=88),
        Employee(name="Харитонов Аркадий", position="DevOps", department="ИТ", rating=91, tasks=14, speed=7, correctness=96, score=94),
        Employee(name="Белова Светлана", position="HR", department="Кадры", rating=80, tasks=6, speed=3, correctness=97, score=86),
        Employee(name="Сергеев Тимур", position="Тестировщик", department="QA", rating=85, tasks=10, speed=5, correctness=94, score=88),
        Employee(name="Власова Карина", position="Дизайнер", department="Маркетинг", rating=82, tasks=8, speed=4, correctness=92, score=86),
    ]
    db.session.bulk_save_objects(employees)
    db.session.commit()
    print("50 сотрудников добавлены!")
